name: Build & Release

on:
    push:
        branches: ['main']

jobs:
    build_on_mac:
        runs-on: macos-latest
        environment: production
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18.13.0
            - name: install dependencies
              run: npm run install:all
            - name: build
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: ./dist/*.dmg; ./dist/*.dmg.blockmap; ./dist/*mac.zip; ./dist/*.zip.blockmap; ./dist/latest-mac.yml;
                  tags: false
                  draft: false
                  tag_name: v0.0.${{ github.run_number }}

    build_on_ubuntu:
        runs-on: ubuntu-latest
        environment: production
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 20.15.1
            - name: install dependencies
              run: npm run install:all
            - name: build
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: ./dist/*.AppImage; ./dist/builder-debug.yml; ./dist/latest-linux.yml;
                  tags: false
                  draft: false
                  tag_name: v0.0.${{ github.run_number }}

    build_on_windows:
        runs-on: windows-latest
        environment: production
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18.13.0
            - name: install dependencies
              run: npm run install:all
            - name: build
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: ./dist/*.exe; ./dist/*.exe.blockmap; ./dist/builder-debug.yml; ./dist/latest.yml;
                  tags: false
                  draft: false
                  tag_name: v0.0.${{ github.run_number }}
