name: Build & Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag name to release (e.g. v2.0.0-beta.5)'
                required: true
                type: string
    push:
        tags: ['v*', '[0-9]*']

permissions: write-all

jobs:
    deploy_macos:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.dmg
                ./dist/*.zip
                ./dist/*.zip.blockmap
                ./dist/latest-mac.yml
            runs-on: 'macos-latest'
            tag: ${{ inputs.tag || '' }}

    deploy_linux:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.AppImage
                ./dist/latest-linux.yml
            runs-on: 'ubuntu-latest'
            tag: ${{ inputs.tag || '' }}

    deploy_windows:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.exe
                ./dist/*.exe.blockmap
                ./dist/latest.yml
            runs-on: 'windows-latest'
            tag: ${{ inputs.tag || '' }}
