name: Build & Release

on:
    push:
        tags: ['v*']

permissions: write-all

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Get Last Commit Message
              id: get_commit
              run: |
                  # Get the tag name from the current reference
                  TAG_NAME="${GITHUB_REF_NAME}"
                  # Get the last commit message for the tag
                  LAST_COMMIT_MSG=$(git log -1 --pretty=format:"%s" "$TAG_NAME")
                  echo "Last commit message: $LAST_COMMIT_MSG"
                  echo "commit_message=$LAST_COMMIT_MSG" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  body: |
                      `${{ env.commit_message }}`
                      "\n Download links should be ready in a few minutes."

    deploy_macos:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.dmg
                ./dist/*mac.zip 
                ./dist/*.zip.blockmap 
                ./dist/latest-mac.yml
            runs-on: 'macos-latest'

    deploy_linux:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.AppImage
                ./dist/latest-linux.yml
            runs-on: 'ubuntu-latest'

    deploy_windows:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.exe
                ./dist/*.exe.blockmap
                ./dist/latest.yml
            runs-on: 'windows-latest'
