name: Build & Release

on:
    push:
        branches: ['main']

permissions:
    contents: write
    deployments: write

jobs:
    deploy_macos:
        uses: ./.github/workflows/deploy.yml
        with:
            file: './dist/*.dmg; ./dist/*.dmg.blockmap; ./dist/*mac.zip; ./dist/*.zip.blockmap; ./dist/latest-mac.yml;'
            runs-on: 'macos-latest'

    deploy_linux:
        uses: ./.github/workflows/deploy.yml
        with:
            file: './dist/*.AppImage; ./dist/builder-debug.yml; ./dist/latest-linux.yml;'
            runs-on: 'ubuntu-latest'

    deploy_windows:
        uses: ./.github/workflows/deploy.yml
        with:
            file: './dist/*.exe; ./dist/*.exe.blockmap; ./dist/builder-debug.yml; ./dist/latest.yml;'
            runs-on: 'windows-latest'
