name: Build

on:
    workflow_call:
        inputs:
            runs-on:
                required: true
                type: string
            file:
                required: true
                type: string

jobs:
    deploy:
        runs-on: ${{ github.event.inputs.runs-on }}
        environment: production
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 20.15.1
            - name: install dependencies
              run: npm run install:all
            - name: build
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: ./dist/*.dmg; ./dist/*.dmg.blockmap; ./dist/*mac.zip; ./dist/*.zip.blockmap; ./dist/latest-mac.yml;
                  tags: false
                  draft: false
                  tag_name: v0.0.${{ github.run_number }}
