name: Discord Release

on:
    release:
        types:
            - released

jobs:
    notify-discord:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Notify Discord
              uses: SethCohen/github-releases-to-discord@v1.16.2
              with:
                  webhook_url: ${{ secrets.DISCORD_RELEASE_WEBHOOK_URL }}
                  color: '2105893'
                  username: 'Release Changelog'
                  avatar_url: 'https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png'
                  content: |
                      **New Release Published: ${{ github.event.release.tag_name }}**
                      ${{ github.event.release.body || 'No release notes provided.' }}
                  footer_title: 'Changelog'
                  footer_icon_url: 'https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png'
                  footer_timestamp: true
