name: Install Modules

on:
    push:
        branches: ['main']

jobs:
    build_on_ubuntu:
        runs-on: ubuntu-20.04
        environment: production
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18.13.0
            - name: install dependencies
              run: npm run i
